openapi: 3.0.0

info:
  title: Hello Module for EpiCRM
  description: EpiCRM Hello Module OpenAPI sepcification
  version: 0.1.0

paths:
  /hello:
    get:
      description: Hello endpoint
      tags:
        - hello
      responses:
        '200':
          description: 'Says "world"'
